GET http://localhost:3000/movies/

###

POST http://localhost:3000/movies/
Content-Type: application/json

{
    "directorId": 6,
    "movieName" : "Jurasic Park",
    "leadActor" : "jeff Goldbulm"
}

###

GET http://localhost:3000/movies/21
###

PUT http://localhost:3000/movies/9/

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###

DELETE http://localhost:3000/movies/:movieId/

###

GET http://localhost:3000/directors/
###

GET http://localhost:3000/directors/:directorId/movies/
###